node {
   git '/tmp/repo'

   docker.withRegistry('https://docker.example.com/', 'docker-registry-login') {
    
     stage 'Build and Run Docker Image 1.0'
     sh 'cp demoapp/Docker_v1.0 demoapp/Dockerfile'
     def pcImg = docker.build('demoapp:1.0','demoapp')
     def container = pcImg.run('-d -i -p 8082:8080')
     input "How does v1.0 look?"
     container.stop()

     stage 'Build and Run Docker Image 2.0'
     sh 'cp demoapp/Docker_v2.0 demoapp/Dockerfile'
     pcImg = docker.build('demoapp:2.0','demoapp')
     container = pcImg.run('-d -i -p 8082:8080')
     input "How does v2.0 look?"
     container.stop()

     stage 'Build and Run Docker Image 2.1'
     sh 'cp demoapp/Docker_v2.1 demoapp/Dockerfile'
     pcImg = docker.build('demoapp:2.1','demoapp')
     container = pcImg.run('-d -i -p 8082:8080')
     input "How does v2.1 look?"
     container.stop()

     stage 'Build and Run Docker Image 3.0'
     sh 'cp demoapp/Docker_v3.0 demoapp/Dockerfile'
     pcImg = docker.build('demoapp:3.0','demoapp')
     container = pcImg.run('-d -i -p 8082:8080')
     input "How does v3.0 look?"
     container.stop()

   }
}

